config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#home'
  post 'submitted_contact', to:'home#submitted'
  get 'contact',  to: 'home#contact'
  resources :locations, :only => :show
  #Only specifies which routes rails should create for the model
  #:show is the attribute of the controller. the website will only create show route
  #I want this so the user cannot edit the locations, destroy or create new ones
  #Any locations that should be added should be edited in db:seed file

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

add_flash_types :danger, :info, :success, :warning
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
  def contact
  end
  def submitted
    name = params[:name]
    email = params[:email]
    message = params[:message]
    if (name.blank? || email.blank? || message.blank?)
      flash[:danger] = "Form not submitted, all fields need to be filled"
      redirect_to contact_path

    else
      ContactMailer.contact_email(name,email,message).deliver_now
      flash[:success] = "Message has been sent"
      redirect_to root_path
    end



  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end
  def name
    @name
  end


  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :latitude, :longitude, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/home/contact.html.haml
%h1=t('.title')
%p=t('.contact_us')

= form_tag submitted_contact_path, method: "post", name: "myForm" do
  =label_tag t('.name')
  %br
  =text_field_tag "name"
  %br
  =label_tag t('.email')
  %br
  =email_field_tag 'email'
  %br
  =label_tag t('.message')
  %br
  =text_area_tag 'message'
  %br
  %br
  %input.btn.btn-success{:type=>"submit",:name=>"submit",:value=>t('.submit_message')}

:javascript
  function validateForm(){
    var name = $('#name').val();
    var email = $('#email').val();
    var message = $('#message').val();
    if (name == "" || email == "" || message == ""){
      alert("All fields are required");
      
    }
    else {

    }
  }
  $("form[name='myForm']").submit(validateForm);

app/views/home/home.html.haml
.container
  .jumbotron{:style=>"background-color:#00CDAC;"}
    %h1=t('.guildfordpark')
    %p=t('.gparkdesc')
    .whatToDo
      %h2=t('.instructions')
  .jumbotron{:style=>"background-color:#00CDAC;"}
    %ul{:style=>"list-style-type:none;"}
      %li.homeMenu
        %h1
          %a{:href=>"/users/sign_up", :role=>"button"}=t('.create_account')
      %li.homeMenu
        %h1
          %a{:href=>"/users/sign_in", :role=>"button"}=t('.sign_in')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Guildford Parking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'shared/gmapSetup'

  %body

    = render 'shared/navbar'
    = render 'shared/flashmessages'
    = yield

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :capacity
    = f.number_field :capacity
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %thead
    %tr
      %th Name
      %th Latitude
      %th Longitude
      %th Capacity
      %th
      %th
      %th

  %tbody
    - @locations.each do |location|
      %tr
        %td= location.name
        %td= location.latitude
        %td= location.longitude
        %td= location.capacity
        %td= link_to 'Show', location
        %td= link_to 'Edit', edit_location_path(location)
        %td= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
#map

  :javascript
    var lat = #{@location.latitude};
    var long = #{@location.longitude};
    var map = new GMaps({
      div: '#map',
      lat: lat,
      lng: long,


    });
    var loc = #{@location.capacity}
    map.addMarker({
    lat: lat,
    lng: long,
    infoWindow:{
    content: "Name: #{@location.name}"+"<br>"+"Capacity: "+"#{@location.capacity}"
    }});

app/views/shared/_flashmessages.html.haml
- if notice
  %p.alert.alert-success= notice
- if alert
  %p.alert.alert-danger= alert

app/views/shared/_gmapSetup.html.haml
%script{async: "", defer: "defer", src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyASznYehOYVIsxrVrAdRveLGxJGtA8QELE&callback=initMap", type: "text/javascript"}
%script{src: "http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js", type: "text/javascript"}
%script{src: "http://maps.google.com/maps/api/js?sensor=true", type: "text/javascript"}
%script{src: "../gmaps.js", type: "text/javascript"}
%script{src: "http://maps.google.com/maps/api/js"}
%script{src: "gmaps.js"}
:css
  #map {
    width: 400px;
    height: 400px;
  }

app/views/shared/_navbar.html.haml
%nav.navbar{:style=>"background-color:#00CDAC;"}
  %ul.nav.navbar-nav
    %li
      %a{:href=>"/"}
        %img{:src=>"https://media.glassdoor.com/sqll/1441029/guildford-borough-council-squarelogo-1519723186274.png",:width=>"50px",:height=>"50px",:style=>"position:relative;"}



    %li
      %a{:href=>"/",:alt=>"Home"}=t('home_nav')
    %li
      %a{:href=>"/contact"}=t('contact_nav')
    %li.dropdown
      %a.dropdown-toggle{:href=>"#","data-toggle"=>"dropdown"}
        =t('locations_nav')
        %span.caret
      %ul.dropdown-menu
        %li
          -@location = Location.all
          -@location.each do |l|
            %a{:href=>"/locations/#{l.id}"}=l.name

    %li
      - if user_signed_in?
        =link_to t('logout'), destroy_user_session_path, method: :delete